Source/CloudMedia.Remote.Cloud.Web.UI/Controllers/GuideController.cs
using System;
using System.Web.Mvc;
using System.Web.UI;
using CloudMedia.Remote.Cloud.Web.UI.Controllers.Commands;
using CloudMedia.Remote.Cloud.Web.UI.Models;
using CloudMedia.Remote.Framework.Command;

namespace CloudMedia.Remote.Cloud.Web.UI.Controllers
{
    public class GuideController : SuperController
    {
        private readonly ICommandAbstractFactory _commandAbstractFactory;

        public GuideController(ICommandAbstractFactory commandAbstractFactory)
        {
            _commandAbstractFactory = commandAbstractFactory;
        }

        [AuthenticateAndAuthorize(Roles = "Reader")]
        [OutputCache(Duration = 300, Location = OutputCacheLocation.Any)]
        public ActionResult Index()
        {
            ViewBag.Message = ViewBag.Authorization.IsAdministrator ? "Here you can view the electronic programme guide and record TV shows" : "Here you can view the electronic programme guide";

            return View(new GuideModel());
        }

        [AuthenticateAndAuthorize(Roles = "Admin")]
        public ActionResult Record()
        {
            ViewBag.Message = ViewBag.Authorization.IsAdministrator ? "Here you can view the electronic programme guide and record TV shows" : "Here you can view the electronic programme guide";
            var context = new RecordTvShowContext();
            _commandAbstractFactory.ExecuteCommand(context);
            return View("Index", context.GuideModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your quintessential app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your quintessential contact page.";

            return View();
        }
    }
}

Source/CloudMedia.Remote.Cloud.Web.UI/Controllers/StatisticsController.cs
using System.ServiceModel;
using System.Web.Mvc;
using CloudMedia.Remote.Cloud.Web.UI.Controllers.Commands;
using CloudMedia.Remote.Framework.Command;

namespace CloudMedia.Remote.Cloud.Web.UI.Controllers
{
    [HandleError(ExceptionType = typeof(EndpointNotFoundException), View = "ServiceBusNotAvailable")]
    [AuthenticateAndAuthorize(Roles = "Reader")]
    public class StatisticsController : SuperController
    {
        private readonly ICommandAbstractFactory _commandAbstractFactory;

        public StatisticsController(ICommandAbstractFactory commandAbstractFactory)
        {
            _commandAbstractFactory = commandAbstractFactory;
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Displays various information about the media centre being used.";
            var context = new RetrieveMediaCentreStatisticsContext();
            _commandAbstractFactory.ExecuteCommand(context);
        
            return View(context.StatisticsModel);
        }

    }
}

Source/CloudMedia.Remote.Cloud.Web.UI/Views/Shared/AuthorizationError.cshtml
@{
    ViewBag.Title = "Authorization Error";
}

<hgroup class="title">
    <h1 class="error">Error.</h1>
    <h2 class="error">You are not authorised to use this feature.</h2>
</hgroup>

Source/CloudMedia.Remote.Cloud.Web.UI/Views/Shared/ServiceBusNotAvailable.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<hgroup class="title">
    <h1 class="error">Error.</h1>
    <h2 class="error">It appears the relay service to deliver the content you are requesting is not available at the moment. This could
    be due to the Media Center machine is not running. Please try again later.</h2>
</hgroup>

Source/CloudMedia.Remote.Cloud.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Windows Media Remote Control</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/AjaxLogin.js")" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width">
</head>
<body>
    <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("remote media control", "Index", "Guide")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LogOnPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>  
                                                     
                            @if (ViewBag.Authorization != null && (ViewBag.Authorization.IsAdministrator || ViewBag.Authorization.IsReader))
                            {
                                <li>@Html.ActionLink("Media Centre Statistics", "Index", "Statistics")</li>
                                <li>@Html.ActionLink("Television Guide", "Index", "Guide")</li>
                            }                            
                            <li>@Html.ActionLink("About", "About", "Guide")</li>                           
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    <div id="body">
        @RenderSection("featured", false)
        <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
    </div>
    <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Windows Media Centre Remote Control</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://twitter.com/simonrhart" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
</body>
</html>

Source/CloudMedia.Remote.Cloud.Web.UI/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <p>
        Hello, @Html.ActionLink(User.Identity.Name, "ChangePassword", "Account", null, new { @class = "username" })!
        @Html.ActionLink("Log Off", "LogOff", "Account")
    </p>
} else {
    <ul>
        <li>@Html.ActionLink("Log on", "LogOn", "Account")</li>
    </ul>
}